import Footer from "@/components/footer/Footer";
import "./globals.css";
import Navigation1 from "@/components/navigation/Navigation1";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Navigation1 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
