import Footer from "@/components/footer/Footer";
import "./globals.css";
import Navigation from "@/components/navigation/Navigation";
import { Inter } from "next/font/google";
import "@fontsource/source-sans-pro";
import "@fontsource-variable/oswald";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={` relative`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
